#!/bin/bash

set -e

function craine_module_deskto_loader() {

    ## ENVIRONMENTS
    local dekst_dirs="$applibs/libguis"

    if [[ $distro_destop == "cosmic" ]];then
        deskt_type="$dekst_dirs/cosmic"
    elif [[ $distro_destop == "budgie" ]];then
        deskt_type="$dekst_dirs/budgie"
    elif [[ $distro_destop == "ukui" ]];then
        deskt_type="$dekst_dirs/deukue"
    elif [[ $distro_destop == "cutefish" ]];then
        deskt_type="$dekst_dirs/cutefes"
    elif [[ $distro_destop == "lxqt" ]];then
        deskt_type="$dekst_dirs/winlxqt"
    elif [[ $distro_destop == "bodhi" ]];then
        deskt_type="$dekst_dirs/bodhis"
    elif [[ $distro_destop == "lxde" ]];then
        deskt_type="$dekst_dirs/winlxde"
     elif [[ $distro_destop == "blackbox" ]];then
        deskt_type="$dekst_dirs/blacbo"
    elif [[ $distro_destop == "pantheon" ]];then
        deskt_type="$dekst_dirs/panthe"
    elif [[ $distro_destop == "deepin" ]];then
        deskt_type="$dekst_dirs/deepin"
    elif [[ $distro_destop == "gnome" ]];then
        deskt_type="$dekst_dirs/gnome"
    elif [[ $distro_destop == "sugar" ]];then
        deskt_type="$dekst_dirs/sugars"
    elif [[ $distro_destop == "hyperland" ]];then
        deskt_type="$dekst_dirs/hypers"
    elif [[ $distro_destop == "plasma" ]];then
        deskt_type="$dekst_dirs/plasma"
    elif [[ $distro_destop == "xfce4" ]];then
        deskt_type="$dekst_dirs/dexfce"
    fi

    deskt_path="$deskt_type/101"
   
    ## LOAD MODULES
    if [[ -n $deskt_type ]]; then
        test -d "$deskt_type/$protoc_destop" && deskt_path="$deskt_type/$protoc_destop"
        test -e "$deskt_path/module" && cat "$deskt_path/module" >>   "$raptor_packer"
        test -e "$deskt_path/config" && cp -fr "$deskt_path/config/"* "$raptor_config"
        echo "Desktop environment loaded"
    fi
}

craine_module_deskto_loader