#!/bin/bash

set -e

function craine_module_disks_loader() {

    ## ENVIRONMENTS
    local disks_dirs="$applibs/libdisk"
    disks_path="$disks_dirs/101"
    

    ## LOAD MODULES    
    test -d "$disks_dirs/$protoc_storag"  && disks_path="$disks_dirs/$protoc_storag"
    test -e "$disks_path/module" && cat "$disks_path/module" >>  "$raptor_packer"
    test -e "$disks_path/config" && cp -fr "$disks_path/config/"* "$raptor_config"
    echo "Storage system environment loaded"
}

craine_module_disks_loader